/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.analysis;

import prefixa.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTVazio(TVazio node);
    void caseTAtribuicao(TAtribuicao node);
    void caseTChar(TChar node);
    void caseTInt(TInt node);
    void caseTVariable(TVariable node);
    void caseTNumero(TNumero node);
    void caseTSoma(TSoma node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTComma(TComma node);
    void caseTDoubleDot(TDoubleDot node);
    void caseTStartBlock(TStartBlock node);
    void caseTEndBlock(TEndBlock node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTWhile(TWhile node);
    void caseTDo(TDo node);
    void caseTFor(TFor node);
    void caseTEach(TEach node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTLBrace(TLBrace node);
    void caseTRBrace(TRBrace node);
    void caseTEq(TEq node);
    void caseTNeq(TNeq node);
    void caseTLt(TLt node);
    void caseTLteq(TLteq node);
    void caseTGt(TGt node);
    void caseTGteq(TGteq node);
    void caseTSemicolon(TSemicolon node);
    void caseTScan(TScan node);
    void caseTPrint(TPrint node);
    void caseTString(TString node);
    void caseTComments(TComments node);
    void caseTLongComment(TLongComment node);
    void caseEOF(EOF node);
}
