/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import java.util.*;
import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class ABloco extends PBloco
{
    private TStartBlockId _startBlockId_;
    private final LinkedList<PDeclVar> _declVar_ = new LinkedList<PDeclVar>();
    private final LinkedList<PComando> _comando_ = new LinkedList<PComando>();
    private TEndBlockId _endBlockId_;

    public ABloco()
    {
        // Constructor
    }

    public ABloco(
        @SuppressWarnings("hiding") TStartBlockId _startBlockId_,
        @SuppressWarnings("hiding") List<PDeclVar> _declVar_,
        @SuppressWarnings("hiding") List<PComando> _comando_,
        @SuppressWarnings("hiding") TEndBlockId _endBlockId_)
    {
        // Constructor
        setStartBlockId(_startBlockId_);

        setDeclVar(_declVar_);

        setComando(_comando_);

        setEndBlockId(_endBlockId_);

    }

    @Override
    public Object clone()
    {
        return new ABloco(
            cloneNode(this._startBlockId_),
            cloneList(this._declVar_),
            cloneList(this._comando_),
            cloneNode(this._endBlockId_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABloco(this);
    }

    public TStartBlockId getStartBlockId()
    {
        return this._startBlockId_;
    }

    public void setStartBlockId(TStartBlockId node)
    {
        if(this._startBlockId_ != null)
        {
            this._startBlockId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._startBlockId_ = node;
    }

    public LinkedList<PDeclVar> getDeclVar()
    {
        return this._declVar_;
    }

    public void setDeclVar(List<PDeclVar> list)
    {
        this._declVar_.clear();
        this._declVar_.addAll(list);
        for(PDeclVar e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public LinkedList<PComando> getComando()
    {
        return this._comando_;
    }

    public void setComando(List<PComando> list)
    {
        this._comando_.clear();
        this._comando_.addAll(list);
        for(PComando e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TEndBlockId getEndBlockId()
    {
        return this._endBlockId_;
    }

    public void setEndBlockId(TEndBlockId node)
    {
        if(this._endBlockId_ != null)
        {
            this._endBlockId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endBlockId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._startBlockId_)
            + toString(this._declVar_)
            + toString(this._comando_)
            + toString(this._endBlockId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._startBlockId_ == child)
        {
            this._startBlockId_ = null;
            return;
        }

        if(this._declVar_.remove(child))
        {
            return;
        }

        if(this._comando_.remove(child))
        {
            return;
        }

        if(this._endBlockId_ == child)
        {
            this._endBlockId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._startBlockId_ == oldChild)
        {
            setStartBlockId((TStartBlockId) newChild);
            return;
        }

        for(ListIterator<PDeclVar> i = this._declVar_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDeclVar) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PComando> i = this._comando_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComando) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._endBlockId_ == oldChild)
        {
            setEndBlockId((TEndBlockId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
