/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class ABoolfalseConstante extends PConstante
{
    private TFalseId _falseId_;

    public ABoolfalseConstante()
    {
        // Constructor
    }

    public ABoolfalseConstante(
        @SuppressWarnings("hiding") TFalseId _falseId_)
    {
        // Constructor
        setFalseId(_falseId_);

    }

    @Override
    public Object clone()
    {
        return new ABoolfalseConstante(
            cloneNode(this._falseId_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolfalseConstante(this);
    }

    public TFalseId getFalseId()
    {
        return this._falseId_;
    }

    public void setFalseId(TFalseId node)
    {
        if(this._falseId_ != null)
        {
            this._falseId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._falseId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._falseId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._falseId_ == child)
        {
            this._falseId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._falseId_ == oldChild)
        {
            setFalseId((TFalseId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
