/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class AComandoAtribComando extends PComando
{
    private PComandoAtrib _comandoAtrib_;

    public AComandoAtribComando()
    {
        // Constructor
    }

    public AComandoAtribComando(
        @SuppressWarnings("hiding") PComandoAtrib _comandoAtrib_)
    {
        // Constructor
        setComandoAtrib(_comandoAtrib_);

    }

    @Override
    public Object clone()
    {
        return new AComandoAtribComando(
            cloneNode(this._comandoAtrib_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoAtribComando(this);
    }

    public PComandoAtrib getComandoAtrib()
    {
        return this._comandoAtrib_;
    }

    public void setComandoAtrib(PComandoAtrib node)
    {
        if(this._comandoAtrib_ != null)
        {
            this._comandoAtrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoAtrib_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoAtrib_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoAtrib_ == child)
        {
            this._comandoAtrib_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoAtrib_ == oldChild)
        {
            setComandoAtrib((PComandoAtrib) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
