/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class ADirectPointerFunction extends PPointerFunction
{
    private TAtribuicao _atribuicao_;
    private PDirectFunctionDeclarator _directFunctionDeclarator_;

    public ADirectPointerFunction()
    {
        // Constructor
    }

    public ADirectPointerFunction(
        @SuppressWarnings("hiding") TAtribuicao _atribuicao_,
        @SuppressWarnings("hiding") PDirectFunctionDeclarator _directFunctionDeclarator_)
    {
        // Constructor
        setAtribuicao(_atribuicao_);

        setDirectFunctionDeclarator(_directFunctionDeclarator_);

    }

    @Override
    public Object clone()
    {
        return new ADirectPointerFunction(
            cloneNode(this._atribuicao_),
            cloneNode(this._directFunctionDeclarator_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADirectPointerFunction(this);
    }

    public TAtribuicao getAtribuicao()
    {
        return this._atribuicao_;
    }

    public void setAtribuicao(TAtribuicao node)
    {
        if(this._atribuicao_ != null)
        {
            this._atribuicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atribuicao_ = node;
    }

    public PDirectFunctionDeclarator getDirectFunctionDeclarator()
    {
        return this._directFunctionDeclarator_;
    }

    public void setDirectFunctionDeclarator(PDirectFunctionDeclarator node)
    {
        if(this._directFunctionDeclarator_ != null)
        {
            this._directFunctionDeclarator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._directFunctionDeclarator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atribuicao_)
            + toString(this._directFunctionDeclarator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atribuicao_ == child)
        {
            this._atribuicao_ = null;
            return;
        }

        if(this._directFunctionDeclarator_ == child)
        {
            this._directFunctionDeclarator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._atribuicao_ == oldChild)
        {
            setAtribuicao((TAtribuicao) newChild);
            return;
        }

        if(this._directFunctionDeclarator_ == oldChild)
        {
            setDirectFunctionDeclarator((PDirectFunctionDeclarator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
