/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class ADirectFunctionDeclarator extends PFunctionDeclarator
{
    private PDirectFunctionDeclarator _directFunctionDeclarator_;

    public ADirectFunctionDeclarator()
    {
        // Constructor
    }

    public ADirectFunctionDeclarator(
        @SuppressWarnings("hiding") PDirectFunctionDeclarator _directFunctionDeclarator_)
    {
        // Constructor
        setDirectFunctionDeclarator(_directFunctionDeclarator_);

    }

    @Override
    public Object clone()
    {
        return new ADirectFunctionDeclarator(
            cloneNode(this._directFunctionDeclarator_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADirectFunctionDeclarator(this);
    }

    public PDirectFunctionDeclarator getDirectFunctionDeclarator()
    {
        return this._directFunctionDeclarator_;
    }

    public void setDirectFunctionDeclarator(PDirectFunctionDeclarator node)
    {
        if(this._directFunctionDeclarator_ != null)
        {
            this._directFunctionDeclarator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._directFunctionDeclarator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._directFunctionDeclarator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._directFunctionDeclarator_ == child)
        {
            this._directFunctionDeclarator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._directFunctionDeclarator_ == oldChild)
        {
            setDirectFunctionDeclarator((PDirectFunctionDeclarator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
