/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class AEqCondicao extends PCondicao
{
    private PValor _valor_;
    private PIgual _igual_;

    public AEqCondicao()
    {
        // Constructor
    }

    public AEqCondicao(
        @SuppressWarnings("hiding") PValor _valor_,
        @SuppressWarnings("hiding") PIgual _igual_)
    {
        // Constructor
        setValor(_valor_);

        setIgual(_igual_);

    }

    @Override
    public Object clone()
    {
        return new AEqCondicao(
            cloneNode(this._valor_),
            cloneNode(this._igual_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqCondicao(this);
    }

    public PValor getValor()
    {
        return this._valor_;
    }

    public void setValor(PValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    public PIgual getIgual()
    {
        return this._igual_;
    }

    public void setIgual(PIgual node)
    {
        if(this._igual_ != null)
        {
            this._igual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._valor_)
            + toString(this._igual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        if(this._igual_ == child)
        {
            this._igual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._valor_ == oldChild)
        {
            setValor((PValor) newChild);
            return;
        }

        if(this._igual_ == oldChild)
        {
            setIgual((PIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
