/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class AEqIgual extends PIgual
{
    private TIgualQue _igualQue_;
    private PValor _valor_;

    public AEqIgual()
    {
        // Constructor
    }

    public AEqIgual(
        @SuppressWarnings("hiding") TIgualQue _igualQue_,
        @SuppressWarnings("hiding") PValor _valor_)
    {
        // Constructor
        setIgualQue(_igualQue_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AEqIgual(
            cloneNode(this._igualQue_),
            cloneNode(this._valor_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqIgual(this);
    }

    public TIgualQue getIgualQue()
    {
        return this._igualQue_;
    }

    public void setIgualQue(TIgualQue node)
    {
        if(this._igualQue_ != null)
        {
            this._igualQue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igualQue_ = node;
    }

    public PValor getValor()
    {
        return this._valor_;
    }

    public void setValor(PValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._igualQue_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._igualQue_ == child)
        {
            this._igualQue_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._igualQue_ == oldChild)
        {
            setIgualQue((TIgualQue) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((PValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
