/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class AExpUnStmt extends PStmt
{
    private PExpUn _expUn_;

    public AExpUnStmt()
    {
        // Constructor
    }

    public AExpUnStmt(
        @SuppressWarnings("hiding") PExpUn _expUn_)
    {
        // Constructor
        setExpUn(_expUn_);

    }

    @Override
    public Object clone()
    {
        return new AExpUnStmt(
            cloneNode(this._expUn_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpUnStmt(this);
    }

    public PExpUn getExpUn()
    {
        return this._expUn_;
    }

    public void setExpUn(PExpUn node)
    {
        if(this._expUn_ != null)
        {
            this._expUn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expUn_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expUn_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expUn_ == child)
        {
            this._expUn_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expUn_ == oldChild)
        {
            setExpUn((PExpUn) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
