/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class AIfelseCondicional extends PCondicional
{
    private PCondicional _condicional_;
    private TElseId _elseId_;
    private PBloco _bloco_;

    public AIfelseCondicional()
    {
        // Constructor
    }

    public AIfelseCondicional(
        @SuppressWarnings("hiding") PCondicional _condicional_,
        @SuppressWarnings("hiding") TElseId _elseId_,
        @SuppressWarnings("hiding") PBloco _bloco_)
    {
        // Constructor
        setCondicional(_condicional_);

        setElseId(_elseId_);

        setBloco(_bloco_);

    }

    @Override
    public Object clone()
    {
        return new AIfelseCondicional(
            cloneNode(this._condicional_),
            cloneNode(this._elseId_),
            cloneNode(this._bloco_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfelseCondicional(this);
    }

    public PCondicional getCondicional()
    {
        return this._condicional_;
    }

    public void setCondicional(PCondicional node)
    {
        if(this._condicional_ != null)
        {
            this._condicional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condicional_ = node;
    }

    public TElseId getElseId()
    {
        return this._elseId_;
    }

    public void setElseId(TElseId node)
    {
        if(this._elseId_ != null)
        {
            this._elseId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elseId_ = node;
    }

    public PBloco getBloco()
    {
        return this._bloco_;
    }

    public void setBloco(PBloco node)
    {
        if(this._bloco_ != null)
        {
            this._bloco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bloco_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._condicional_)
            + toString(this._elseId_)
            + toString(this._bloco_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._condicional_ == child)
        {
            this._condicional_ = null;
            return;
        }

        if(this._elseId_ == child)
        {
            this._elseId_ = null;
            return;
        }

        if(this._bloco_ == child)
        {
            this._bloco_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._condicional_ == oldChild)
        {
            setCondicional((PCondicional) newChild);
            return;
        }

        if(this._elseId_ == oldChild)
        {
            setElseId((TElseId) newChild);
            return;
        }

        if(this._bloco_ == oldChild)
        {
            setBloco((PBloco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
