/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class AIntType extends PType
{
    private TIntId _intId_;

    public AIntType()
    {
        // Constructor
    }

    public AIntType(
        @SuppressWarnings("hiding") TIntId _intId_)
    {
        // Constructor
        setIntId(_intId_);

    }

    @Override
    public Object clone()
    {
        return new AIntType(
            cloneNode(this._intId_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntType(this);
    }

    public TIntId getIntId()
    {
        return this._intId_;
    }

    public void setIntId(TIntId node)
    {
        if(this._intId_ != null)
        {
            this._intId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intId_ == child)
        {
            this._intId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._intId_ == oldChild)
        {
            setIntId((TIntId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
