/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorOpr extends POpr
{
    private TMaiorQue _maiorQue_;
    private PStmt _stmt_;
    private PStmt _stmtL_;

    public AMaiorOpr()
    {
        // Constructor
    }

    public AMaiorOpr(
        @SuppressWarnings("hiding") TMaiorQue _maiorQue_,
        @SuppressWarnings("hiding") PStmt _stmt_,
        @SuppressWarnings("hiding") PStmt _stmtL_)
    {
        // Constructor
        setMaiorQue(_maiorQue_);

        setStmt(_stmt_);

        setStmtL(_stmtL_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorOpr(
            cloneNode(this._maiorQue_),
            cloneNode(this._stmt_),
            cloneNode(this._stmtL_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorOpr(this);
    }

    public TMaiorQue getMaiorQue()
    {
        return this._maiorQue_;
    }

    public void setMaiorQue(TMaiorQue node)
    {
        if(this._maiorQue_ != null)
        {
            this._maiorQue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorQue_ = node;
    }

    public PStmt getStmt()
    {
        return this._stmt_;
    }

    public void setStmt(PStmt node)
    {
        if(this._stmt_ != null)
        {
            this._stmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmt_ = node;
    }

    public PStmt getStmtL()
    {
        return this._stmtL_;
    }

    public void setStmtL(PStmt node)
    {
        if(this._stmtL_ != null)
        {
            this._stmtL_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmtL_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._maiorQue_)
            + toString(this._stmt_)
            + toString(this._stmtL_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._maiorQue_ == child)
        {
            this._maiorQue_ = null;
            return;
        }

        if(this._stmt_ == child)
        {
            this._stmt_ = null;
            return;
        }

        if(this._stmtL_ == child)
        {
            this._stmtL_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._maiorQue_ == oldChild)
        {
            setMaiorQue((TMaiorQue) newChild);
            return;
        }

        if(this._stmt_ == oldChild)
        {
            setStmt((PStmt) newChild);
            return;
        }

        if(this._stmtL_ == oldChild)
        {
            setStmtL((PStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
