/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class AMenosOpr extends POpr
{
    private TMenos _menos_;
    private PStmt _stmt_;
    private PStmt _stmtL_;

    public AMenosOpr()
    {
        // Constructor
    }

    public AMenosOpr(
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PStmt _stmt_,
        @SuppressWarnings("hiding") PStmt _stmtL_)
    {
        // Constructor
        setMenos(_menos_);

        setStmt(_stmt_);

        setStmtL(_stmtL_);

    }

    @Override
    public Object clone()
    {
        return new AMenosOpr(
            cloneNode(this._menos_),
            cloneNode(this._stmt_),
            cloneNode(this._stmtL_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenosOpr(this);
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PStmt getStmt()
    {
        return this._stmt_;
    }

    public void setStmt(PStmt node)
    {
        if(this._stmt_ != null)
        {
            this._stmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmt_ = node;
    }

    public PStmt getStmtL()
    {
        return this._stmtL_;
    }

    public void setStmtL(PStmt node)
    {
        if(this._stmtL_ != null)
        {
            this._stmtL_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmtL_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menos_)
            + toString(this._stmt_)
            + toString(this._stmtL_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._stmt_ == child)
        {
            this._stmt_ = null;
            return;
        }

        if(this._stmtL_ == child)
        {
            this._stmtL_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._stmt_ == oldChild)
        {
            setStmt((PStmt) newChild);
            return;
        }

        if(this._stmtL_ == oldChild)
        {
            setStmtL((PStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
