/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class AMneqCondicao extends PCondicao
{
    private PValor _valor_;
    private PMenorIgual _menorIgual_;

    public AMneqCondicao()
    {
        // Constructor
    }

    public AMneqCondicao(
        @SuppressWarnings("hiding") PValor _valor_,
        @SuppressWarnings("hiding") PMenorIgual _menorIgual_)
    {
        // Constructor
        setValor(_valor_);

        setMenorIgual(_menorIgual_);

    }

    @Override
    public Object clone()
    {
        return new AMneqCondicao(
            cloneNode(this._valor_),
            cloneNode(this._menorIgual_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMneqCondicao(this);
    }

    public PValor getValor()
    {
        return this._valor_;
    }

    public void setValor(PValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    public PMenorIgual getMenorIgual()
    {
        return this._menorIgual_;
    }

    public void setMenorIgual(PMenorIgual node)
    {
        if(this._menorIgual_ != null)
        {
            this._menorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menorIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._valor_)
            + toString(this._menorIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        if(this._menorIgual_ == child)
        {
            this._menorIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._valor_ == oldChild)
        {
            setValor((PValor) newChild);
            return;
        }

        if(this._menorIgual_ == oldChild)
        {
            setMenorIgual((PMenorIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
