/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class AMqMaior extends PMaior
{
    private TMaiorQue _maiorQue_;
    private PValor _valor_;

    public AMqMaior()
    {
        // Constructor
    }

    public AMqMaior(
        @SuppressWarnings("hiding") TMaiorQue _maiorQue_,
        @SuppressWarnings("hiding") PValor _valor_)
    {
        // Constructor
        setMaiorQue(_maiorQue_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AMqMaior(
            cloneNode(this._maiorQue_),
            cloneNode(this._valor_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMqMaior(this);
    }

    public TMaiorQue getMaiorQue()
    {
        return this._maiorQue_;
    }

    public void setMaiorQue(TMaiorQue node)
    {
        if(this._maiorQue_ != null)
        {
            this._maiorQue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorQue_ = node;
    }

    public PValor getValor()
    {
        return this._valor_;
    }

    public void setValor(PValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._maiorQue_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._maiorQue_ == child)
        {
            this._maiorQue_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._maiorQue_ == oldChild)
        {
            setMaiorQue((TMaiorQue) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((PValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
