/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class AOprStmt extends PStmt
{
    private POpr _opr_;

    public AOprStmt()
    {
        // Constructor
    }

    public AOprStmt(
        @SuppressWarnings("hiding") POpr _opr_)
    {
        // Constructor
        setOpr(_opr_);

    }

    @Override
    public Object clone()
    {
        return new AOprStmt(
            cloneNode(this._opr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOprStmt(this);
    }

    public POpr getOpr()
    {
        return this._opr_;
    }

    public void setOpr(POpr node)
    {
        if(this._opr_ != null)
        {
            this._opr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opr_ == child)
        {
            this._opr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opr_ == oldChild)
        {
            setOpr((POpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
