/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class ARealType extends PType
{
    private TRealId _realId_;

    public ARealType()
    {
        // Constructor
    }

    public ARealType(
        @SuppressWarnings("hiding") TRealId _realId_)
    {
        // Constructor
        setRealId(_realId_);

    }

    @Override
    public Object clone()
    {
        return new ARealType(
            cloneNode(this._realId_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARealType(this);
    }

    public TRealId getRealId()
    {
        return this._realId_;
    }

    public void setRealId(TRealId node)
    {
        if(this._realId_ != null)
        {
            this._realId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._realId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._realId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._realId_ == child)
        {
            this._realId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._realId_ == oldChild)
        {
            setRealId((TRealId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
