/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class ATipoTipoRetornoFunc extends PTipoRetornoFunc
{
    private PTipo _tipo_;

    public ATipoTipoRetornoFunc()
    {
        // Constructor
    }

    public ATipoTipoRetornoFunc(
        @SuppressWarnings("hiding") PTipo _tipo_)
    {
        // Constructor
        setTipo(_tipo_);

    }

    @Override
    public Object clone()
    {
        return new ATipoTipoRetornoFunc(
            cloneNode(this._tipo_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATipoTipoRetornoFunc(this);
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
