/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class AVariosTypeList extends PTypeList
{
    private PType _type_;
    private TComma _comma_;
    private PTypeList _types_;

    public AVariosTypeList()
    {
        // Constructor
    }

    public AVariosTypeList(
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PTypeList _types_)
    {
        // Constructor
        setType(_type_);

        setComma(_comma_);

        setTypes(_types_);

    }

    @Override
    public Object clone()
    {
        return new AVariosTypeList(
            cloneNode(this._type_),
            cloneNode(this._comma_),
            cloneNode(this._types_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariosTypeList(this);
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PTypeList getTypes()
    {
        return this._types_;
    }

    public void setTypes(PTypeList node)
    {
        if(this._types_ != null)
        {
            this._types_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._types_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._comma_)
            + toString(this._types_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._types_ == child)
        {
            this._types_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._types_ == oldChild)
        {
            setTypes((PTypeList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
