/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class TNoneId extends Token
{
    public TNoneId()
    {
        super.setText("none");
    }

    public TNoneId(int line, int pos)
    {
        super.setText("none");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNoneId(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNoneId(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNoneId text.");
    }
}
