/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class TScan extends Token
{
    public TScan()
    {
        super.setText("scan");
    }

    public TScan(int line, int pos)
    {
        super.setText("scan");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TScan(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTScan(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TScan text.");
    }
}
