/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.node;

import prefixa.analysis.*;

@SuppressWarnings("nls")
public final class TStart extends Token
{
    public TStart()
    {
        super.setText("start");
    }

    public TStart(int line, int pos)
    {
        super.setText("start");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStart(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStart(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStart text.");
    }
}
