/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.lexer;

import java.io.*;
import prefixa.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazio(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCharId(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIntId(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolId(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRealId(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBarraId(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIfId(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElseId(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStartBlockId(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEndBlockId(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNotId(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAndId(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOrId(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNoneId(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSoma(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoubleDot(line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolType(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TForeach(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBracket(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBracket(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrace(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrace(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgualQue(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorQue(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgualQue(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorQue(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorIgualQue(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTrueId(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalseId(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVectorId(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReturn(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TScan(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrint(line, pos); }
    Token new44(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new45(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCharVar(text, line, pos); }
    Token new46(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComments(text, line, pos); }
    Token new47(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLongComment(text, line, pos); }
    Token new48(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIntType(text, line, pos); }
    Token new49(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRealType(text, line, pos); }
    Token new50(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }
    Token new51(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }
    Token new52(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumeroBin(text, line, pos); }
    Token new53(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new THexNumber(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {35, 35, 6}, {37, 37, 7}, {39, 39, 8}, {40, 40, 9}, {41, 41, 10}, {42, 42, 11}, {43, 43, 12}, {44, 44, 13}, {45, 45, 14}, {47, 47, 15}, {48, 48, 16}, {49, 57, 17}, {58, 58, 18}, {59, 59, 19}, {60, 60, 20}, {61, 61, 21}, {62, 62, 22}, {65, 90, 23}, {91, 91, 24}, {93, 93, 25}, {95, 95, 23}, {97, 97, 26}, {98, 98, 27}, {99, 99, 28}, {100, 100, 29}, {101, 101, 30}, {102, 102, 31}, {103, 104, 23}, {105, 105, 32}, {106, 109, 23}, {110, 110, 33}, {111, 111, 34}, {112, 112, 35}, {113, 113, 23}, {114, 114, 36}, {115, 115, 37}, {116, 116, 38}, {117, 117, 23}, {118, 118, 39}, {119, 119, 40}, {120, 122, 23}, {123, 123, 41}, {124, 124, 42}, {125, 125, 43}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{0, 33, 44}, {34, 34, 45}, {35, 65535, 44}, },
            {{0, 9, 46}, {10, 10, 47}, {11, 65535, 46}, },
            {},
            {{0, 38, 48}, {39, 39, 49}, {40, 65535, 48}, },
            {},
            {},
            {},
            {},
            {},
            {{48, 48, 50}, {49, 57, 51}, },
            {},
            {{46, 46, 52}, {48, 57, 17}, {66, 66, 53}, {69, 69, 54}, {98, 98, 55}, {120, 120, 56}, },
            {{46, 57, -18}, {69, 69, 54}, },
            {},
            {},
            {{60, 60, 57}, {61, 61, 58}, },
            {},
            {{61, 61, 59}, },
            {{48, 57, 60}, {65, 90, 61}, {95, 95, 61}, {97, 122, 61}, },
            {},
            {},
            {{48, 95, -25}, {97, 109, 61}, {110, 110, 62}, {111, 122, 61}, },
            {{48, 95, -25}, {97, 110, 61}, {111, 111, 63}, {112, 122, 61}, },
            {{48, 95, -25}, {97, 103, 61}, {104, 104, 64}, {105, 122, 61}, },
            {{48, 110, -29}, {111, 111, 65}, {112, 122, 61}, },
            {{48, 95, -25}, {97, 107, 61}, {108, 108, 66}, {109, 109, 61}, {110, 110, 67}, {111, 122, 61}, },
            {{48, 95, -25}, {97, 97, 68}, {98, 110, 61}, {111, 111, 69}, {112, 122, 61}, },
            {{48, 95, -25}, {97, 101, 61}, {102, 102, 70}, {103, 109, 61}, {110, 110, 71}, {111, 122, 61}, },
            {{48, 110, -29}, {111, 111, 72}, {112, 122, 61}, },
            {{48, 95, -25}, {97, 113, 61}, {114, 114, 73}, {115, 122, 61}, },
            {{48, 113, -36}, {114, 114, 74}, {115, 122, 61}, },
            {{48, 95, -25}, {97, 100, 61}, {101, 101, 75}, {102, 122, 61}, },
            {{48, 95, -25}, {97, 98, 61}, {99, 99, 76}, {100, 100, 61}, {101, 101, 77}, {102, 115, 61}, {116, 116, 78}, {117, 122, 61}, },
            {{48, 113, -36}, {114, 114, 79}, {115, 122, 61}, },
            {{48, 100, -38}, {101, 101, 80}, {102, 122, 61}, },
            {{48, 103, -30}, {104, 104, 81}, {105, 122, 61}, },
            {{123, 123, 82}, {125, 125, 83}, },
            {},
            {},
            {{0, 65535, -7}, },
            {},
            {{0, 65535, -8}, },
            {},
            {{0, 65535, -10}, },
            {},
            {{46, 46, 52}, {48, 57, 51}, {66, 98, -18}, },
            {{46, 57, -52}, {69, 69, 54}, },
            {{48, 57, 84}, },
            {{48, 48, 85}, {49, 49, 86}, },
            {{45, 45, 87}, {48, 57, 88}, },
            {{48, 49, -55}, },
            {{48, 57, 89}, {65, 70, 90}, {97, 102, 91}, },
            {},
            {},
            {},
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 95, -25}, {97, 99, 61}, {100, 100, 92}, {101, 122, 61}, },
            {{48, 110, -29}, {111, 111, 93}, {112, 122, 61}, },
            {{48, 95, -25}, {97, 97, 94}, {98, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 95, -25}, {97, 114, 61}, {115, 115, 95}, {116, 122, 61}, },
            {{48, 99, -64}, {100, 100, 96}, {101, 122, 61}, },
            {{48, 107, -32}, {108, 108, 97}, {109, 122, 61}, },
            {{48, 113, -36}, {114, 114, 98}, {115, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 95, -25}, {97, 115, 61}, {116, 116, 99}, {117, 122, 61}, },
            {{48, 109, -28}, {110, 110, 100}, {111, 115, 61}, {116, 116, 101}, {117, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 95, -25}, {97, 104, 61}, {105, 105, 102}, {106, 122, 61}, },
            {{48, 95, -25}, {97, 97, 103}, {98, 122, 61}, },
            {{48, 95, -25}, {97, 97, 104}, {98, 122, 61}, },
            {{48, 109, -28}, {110, 110, 105}, {111, 122, 61}, },
            {{48, 95, -25}, {97, 97, 106}, {98, 122, 61}, },
            {{48, 95, -25}, {97, 116, 61}, {117, 117, 107}, {118, 122, 61}, },
            {{48, 115, -73}, {116, 116, 108}, {117, 122, 61}, },
            {{48, 104, -76}, {105, 105, 109}, {106, 122, 61}, },
            {{123, 125, -43}, },
            {},
            {{48, 57, 84}, {69, 69, 54}, },
            {{48, 49, -55}, },
            {{48, 49, -55}, },
            {{48, 57, 88}, },
            {{48, 57, 88}, },
            {{48, 102, -58}, },
            {{48, 102, -58}, },
            {{48, 102, -58}, },
            {{48, 122, -25}, },
            {{48, 107, -32}, {108, 108, 110}, {109, 122, 61}, },
            {{48, 113, -36}, {114, 114, 111}, {115, 122, 61}, },
            {{48, 100, -38}, {101, 101, 112}, {102, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 114, -68}, {115, 115, 113}, {116, 122, 61}, },
            {{32, 32, 114}, {48, 122, -25}, },
            {{48, 100, -38}, {101, 101, 115}, {102, 122, 61}, },
            {{48, 100, -38}, {101, 101, 116}, {102, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 109, -28}, {110, 110, 117}, {111, 122, 61}, },
            {{48, 107, -32}, {108, 108, 118}, {109, 122, 61}, },
            {{48, 109, -28}, {110, 110, 119}, {111, 122, 61}, },
            {{48, 99, -64}, {100, 100, 120}, {101, 122, 61}, },
            {{48, 113, -36}, {114, 114, 121}, {115, 122, 61}, },
            {{48, 100, -38}, {101, 101, 122}, {102, 122, 61}, },
            {{48, 110, -29}, {111, 111, 123}, {112, 122, 61}, },
            {{48, 107, -32}, {108, 108, 124}, {109, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 100, -38}, {101, 101, 125}, {102, 122, 61}, },
            {{101, 101, 126}, },
            {{48, 95, -25}, {97, 102, 61}, {103, 103, 127}, {104, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 115, -73}, {116, 116, 128}, {117, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{32, 32, 129}, {48, 122, -25}, },
            {{48, 115, -73}, {116, 116, 130}, {117, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 113, -36}, {114, 114, 131}, {115, 122, 61}, },
            {{48, 100, -38}, {101, 101, 132}, {102, 122, 61}, },
            {{48, 122, -25}, },
            {{97, 97, 133}, },
            {{48, 100, -38}, {101, 101, 134}, {102, 122, 61}, },
            {{48, 122, -25}, },
            {{98, 98, 135}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{99, 99, 136}, },
            {{48, 113, -36}, {114, 114, 137}, {115, 122, 61}, },
            {{97, 97, 138}, },
            {{104, 104, 139}, },
            {{48, 122, -25}, },
            {{99, 99, 140}, },
            {},
            {{107, 107, 141}, },
            {},
        }
        { // COMMENT
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {35, 35, 6}, {37, 37, 7}, {39, 39, 8}, {40, 40, 9}, {41, 41, 10}, {42, 42, 11}, {43, 43, 12}, {44, 44, 13}, {45, 45, 14}, {47, 47, 15}, {48, 48, 16}, {49, 57, 17}, {58, 58, 18}, {59, 59, 19}, {60, 60, 20}, {61, 61, 21}, {62, 62, 22}, {65, 90, 23}, {91, 91, 24}, {93, 93, 25}, {95, 95, 23}, {97, 97, 26}, {98, 98, 27}, {99, 99, 28}, {100, 100, 29}, {101, 101, 30}, {102, 102, 31}, {103, 104, 23}, {105, 105, 32}, {106, 109, 23}, {110, 110, 33}, {111, 111, 34}, {112, 112, 35}, {113, 113, 23}, {114, 114, 36}, {115, 115, 37}, {116, 116, 38}, {117, 117, 23}, {118, 118, 39}, {119, 119, 40}, {120, 122, 23}, {123, 123, 41}, {124, 124, 42}, {125, 125, 43}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{0, 33, 44}, {34, 34, 45}, {35, 65535, 44}, },
            {{0, 9, 46}, {10, 10, 47}, {11, 65535, 46}, },
            {},
            {{0, 38, 48}, {39, 39, 49}, {40, 65535, 48}, },
            {},
            {},
            {},
            {},
            {},
            {{48, 48, 50}, {49, 57, 51}, },
            {},
            {{46, 46, 52}, {48, 57, 17}, {66, 66, 53}, {69, 69, 54}, {98, 98, 55}, {120, 120, 56}, },
            {{46, 57, -18}, {69, 69, 54}, },
            {},
            {},
            {{60, 60, 57}, {61, 61, 58}, },
            {},
            {{61, 61, 59}, },
            {{48, 57, 60}, {65, 90, 61}, {95, 95, 61}, {97, 122, 61}, },
            {},
            {},
            {{48, 95, -25}, {97, 109, 61}, {110, 110, 62}, {111, 122, 61}, },
            {{48, 95, -25}, {97, 110, 61}, {111, 111, 63}, {112, 122, 61}, },
            {{48, 95, -25}, {97, 103, 61}, {104, 104, 64}, {105, 122, 61}, },
            {{48, 110, -29}, {111, 111, 65}, {112, 122, 61}, },
            {{48, 95, -25}, {97, 107, 61}, {108, 108, 66}, {109, 109, 61}, {110, 110, 67}, {111, 122, 61}, },
            {{48, 95, -25}, {97, 97, 68}, {98, 110, 61}, {111, 111, 69}, {112, 122, 61}, },
            {{48, 95, -25}, {97, 101, 61}, {102, 102, 70}, {103, 109, 61}, {110, 110, 71}, {111, 122, 61}, },
            {{48, 110, -29}, {111, 111, 72}, {112, 122, 61}, },
            {{48, 95, -25}, {97, 113, 61}, {114, 114, 73}, {115, 122, 61}, },
            {{48, 113, -36}, {114, 114, 74}, {115, 122, 61}, },
            {{48, 95, -25}, {97, 100, 61}, {101, 101, 75}, {102, 122, 61}, },
            {{48, 95, -25}, {97, 98, 61}, {99, 99, 76}, {100, 100, 61}, {101, 101, 77}, {102, 115, 61}, {116, 116, 78}, {117, 122, 61}, },
            {{48, 113, -36}, {114, 114, 79}, {115, 122, 61}, },
            {{48, 100, -38}, {101, 101, 80}, {102, 122, 61}, },
            {{48, 103, -30}, {104, 104, 81}, {105, 122, 61}, },
            {{123, 123, 82}, {125, 125, 83}, },
            {},
            {},
            {{0, 65535, -7}, },
            {},
            {{0, 65535, -8}, },
            {},
            {{0, 65535, -10}, },
            {},
            {{46, 46, 52}, {48, 57, 51}, {66, 98, -18}, },
            {{46, 57, -52}, {69, 69, 54}, },
            {{48, 57, 84}, },
            {{48, 48, 85}, {49, 49, 86}, },
            {{45, 45, 87}, {48, 57, 88}, },
            {{48, 49, -55}, },
            {{48, 57, 89}, {65, 70, 90}, {97, 102, 91}, },
            {},
            {},
            {},
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 95, -25}, {97, 99, 61}, {100, 100, 92}, {101, 122, 61}, },
            {{48, 110, -29}, {111, 111, 93}, {112, 122, 61}, },
            {{48, 95, -25}, {97, 97, 94}, {98, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 95, -25}, {97, 114, 61}, {115, 115, 95}, {116, 122, 61}, },
            {{48, 99, -64}, {100, 100, 96}, {101, 122, 61}, },
            {{48, 107, -32}, {108, 108, 97}, {109, 122, 61}, },
            {{48, 113, -36}, {114, 114, 98}, {115, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 95, -25}, {97, 115, 61}, {116, 116, 99}, {117, 122, 61}, },
            {{48, 109, -28}, {110, 110, 100}, {111, 115, 61}, {116, 116, 101}, {117, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 95, -25}, {97, 104, 61}, {105, 105, 102}, {106, 122, 61}, },
            {{48, 95, -25}, {97, 97, 103}, {98, 122, 61}, },
            {{48, 95, -25}, {97, 97, 104}, {98, 122, 61}, },
            {{48, 109, -28}, {110, 110, 105}, {111, 122, 61}, },
            {{48, 95, -25}, {97, 97, 106}, {98, 122, 61}, },
            {{48, 95, -25}, {97, 116, 61}, {117, 117, 107}, {118, 122, 61}, },
            {{48, 115, -73}, {116, 116, 108}, {117, 122, 61}, },
            {{48, 104, -76}, {105, 105, 109}, {106, 122, 61}, },
            {{123, 125, -43}, },
            {},
            {{48, 57, 84}, {69, 69, 54}, },
            {{48, 49, -55}, },
            {{48, 49, -55}, },
            {{48, 57, 88}, },
            {{48, 57, 88}, },
            {{48, 102, -58}, },
            {{48, 102, -58}, },
            {{48, 102, -58}, },
            {{48, 122, -25}, },
            {{48, 107, -32}, {108, 108, 110}, {109, 122, 61}, },
            {{48, 113, -36}, {114, 114, 111}, {115, 122, 61}, },
            {{48, 100, -38}, {101, 101, 112}, {102, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 114, -68}, {115, 115, 113}, {116, 122, 61}, },
            {{32, 32, 114}, {48, 122, -25}, },
            {{48, 100, -38}, {101, 101, 115}, {102, 122, 61}, },
            {{48, 100, -38}, {101, 101, 116}, {102, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 109, -28}, {110, 110, 117}, {111, 122, 61}, },
            {{48, 107, -32}, {108, 108, 118}, {109, 122, 61}, },
            {{48, 109, -28}, {110, 110, 119}, {111, 122, 61}, },
            {{48, 99, -64}, {100, 100, 120}, {101, 122, 61}, },
            {{48, 113, -36}, {114, 114, 121}, {115, 122, 61}, },
            {{48, 100, -38}, {101, 101, 122}, {102, 122, 61}, },
            {{48, 110, -29}, {111, 111, 123}, {112, 122, 61}, },
            {{48, 107, -32}, {108, 108, 124}, {109, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 100, -38}, {101, 101, 125}, {102, 122, 61}, },
            {{101, 101, 126}, },
            {{48, 95, -25}, {97, 102, 61}, {103, 103, 127}, {104, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 115, -73}, {116, 116, 128}, {117, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{32, 32, 129}, {48, 122, -25}, },
            {{48, 115, -73}, {116, 116, 130}, {117, 122, 61}, },
            {{48, 122, -25}, },
            {{48, 113, -36}, {114, 114, 131}, {115, 122, 61}, },
            {{48, 100, -38}, {101, 101, 132}, {102, 122, 61}, },
            {{48, 122, -25}, },
            {{97, 97, 133}, },
            {{48, 100, -38}, {101, 101, 134}, {102, 122, 61}, },
            {{48, 122, -25}, },
            {{98, 98, 135}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{99, 99, 136}, },
            {{48, 113, -36}, {114, 114, 137}, {115, 122, 61}, },
            {{97, 97, 138}, },
            {{104, 104, 139}, },
            {{48, 122, -25}, },
            {{99, 99, 140}, },
            {},
            {{107, 107, 141}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 0, 0, 0, 0, -1, -1, 20, -1, 26, 27, 18, 16, 14, 17, 19, 48, 48, 21, 37, 33, 32, 35, 50, 28, 29, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 30, 6, 31, -1, 44, -1, 46, -1, 45, 51, 51, -1, -1, -1, -1, -1, 1, 34, 36, 50, 50, 50, 50, 50, 24, 50, 50, 50, 50, 7, 50, 50, 13, 50, 50, 50, 50, 50, 50, 50, 50, -1, 47, 49, 52, 52, -1, 49, 48, 48, 48, 12, 50, 50, 50, 10, 50, 50, 50, 50, 11, 50, 50, 50, 50, 50, 50, 50, 50, 4, 2, 8, 50, -1, 50, 15, 50, 5, 42, 50, 50, 22, 50, 50, 22, -1, 50, 43, -1, 9, 40, 23, -1, 50, -1, -1, 3, -1, 25, -1, 41, },
        // COMMENT
        {-1, 0, 0, 0, 0, -1, -1, 20, -1, 26, 27, 18, 16, 14, 17, 19, 48, 48, 21, 37, 33, 32, 35, 50, 28, 29, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 30, 6, 31, -1, 44, -1, 46, -1, 45, 51, 51, -1, -1, -1, -1, -1, 1, 34, 36, 50, 50, 50, 50, 50, 24, 50, 50, 50, 50, 7, 50, 50, 13, 50, 50, 50, 50, 50, 50, 50, 50, -1, 47, 49, 52, 52, -1, 49, 48, 48, 48, 12, 50, 50, 50, 10, 50, 50, 50, 50, 11, 50, 50, 50, 50, 50, 50, 50, 50, 4, 2, 8, 50, -1, 50, 15, 50, 5, 42, 50, 50, 22, 50, 50, 22, -1, 50, 43, -1, 9, 40, 23, -1, 50, -1, -1, 3, -1, 25, -1, 41, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMMENT = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
