/* This file was generated by SableCC (http://www.sablecc.org/). */

package prefixa.lexer;

import java.io.*;
import prefixa.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazio(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCharId(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIntId(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolId(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRealId(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIfId(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElseId(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStartBlockId(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEndBlockId(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNotId(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAndId(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOrId(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSoma(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParEsq(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParDir(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoubleDot(line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolType(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFor(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEach(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBracket(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBracket(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrace(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrace(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgualQue(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorQue(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgualQue(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorQue(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorIgualQue(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TScan(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrint(line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComments(text, line, pos); }
    Token new43(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLongComment(text, line, pos); }
    Token new44(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIntType(text, line, pos); }
    Token new45(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRealType(text, line, pos); }
    Token new46(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {35, 35, 6}, {37, 37, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {47, 47, 14}, {48, 48, 15}, {49, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {65, 90, 22}, {91, 91, 23}, {93, 93, 24}, {95, 95, 22}, {97, 97, 25}, {98, 98, 26}, {99, 99, 27}, {100, 100, 28}, {101, 101, 29}, {102, 102, 30}, {103, 104, 22}, {105, 105, 31}, {106, 109, 22}, {110, 110, 32}, {111, 111, 33}, {112, 112, 34}, {113, 113, 22}, {114, 114, 35}, {115, 115, 36}, {116, 116, 37}, {117, 118, 22}, {119, 119, 38}, {120, 122, 22}, {123, 123, 39}, {125, 125, 40}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{0, 33, 41}, {34, 34, 42}, {35, 65535, 41}, },
            {{0, 9, 43}, {10, 10, 44}, {11, 65535, 43}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 45}, },
            {},
            {{46, 46, 46}, {48, 57, 16}, {69, 69, 47}, {120, 120, 48}, },
            {{46, 69, -17}, },
            {},
            {},
            {{60, 60, 49}, {61, 61, 50}, },
            {},
            {{61, 61, 51}, },
            {{48, 57, 52}, {65, 90, 53}, {95, 95, 53}, {97, 122, 53}, },
            {},
            {},
            {{48, 95, -24}, {97, 109, 53}, {110, 110, 54}, {111, 122, 53}, },
            {{48, 95, -24}, {97, 110, 53}, {111, 111, 55}, {112, 122, 53}, },
            {{48, 95, -24}, {97, 103, 53}, {104, 104, 56}, {105, 122, 53}, },
            {{48, 110, -28}, {111, 111, 57}, {112, 122, 53}, },
            {{48, 95, -24}, {97, 97, 58}, {98, 107, 53}, {108, 108, 59}, {109, 109, 53}, {110, 110, 60}, {111, 122, 53}, },
            {{48, 95, -24}, {97, 97, 61}, {98, 110, 53}, {111, 111, 62}, {112, 122, 53}, },
            {{48, 95, -24}, {97, 101, 53}, {102, 102, 63}, {103, 109, 53}, {110, 110, 64}, {111, 122, 53}, },
            {{48, 110, -28}, {111, 111, 65}, {112, 122, 53}, },
            {{48, 95, -24}, {97, 113, 53}, {114, 114, 66}, {115, 122, 53}, },
            {{48, 113, -35}, {114, 114, 67}, {115, 122, 53}, },
            {{48, 95, -24}, {97, 100, 53}, {101, 101, 68}, {102, 122, 53}, },
            {{48, 95, -24}, {97, 98, 53}, {99, 99, 69}, {100, 115, 53}, {116, 116, 70}, {117, 122, 53}, },
            {{48, 113, -35}, {114, 114, 71}, {115, 122, 53}, },
            {{48, 103, -29}, {104, 104, 72}, {105, 122, 53}, },
            {{123, 123, 73}, {125, 125, 74}, },
            {},
            {{0, 65535, -7}, },
            {},
            {{0, 65535, -8}, },
            {},
            {{46, 46, 46}, {48, 57, 45}, {69, 69, 47}, },
            {{48, 57, 75}, },
            {{45, 45, 76}, {48, 57, 77}, },
            {{48, 57, 78}, {65, 70, 79}, {97, 102, 80}, },
            {},
            {},
            {},
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 99, 53}, {100, 100, 81}, {101, 122, 53}, },
            {{48, 110, -28}, {111, 111, 82}, {112, 122, 53}, },
            {{48, 95, -24}, {97, 97, 83}, {98, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 98, -38}, {99, 99, 84}, {100, 122, 53}, },
            {{48, 95, -24}, {97, 114, 53}, {115, 115, 85}, {116, 122, 53}, },
            {{48, 99, -56}, {100, 100, 86}, {101, 122, 53}, },
            {{48, 95, -24}, {97, 107, 53}, {108, 108, 87}, {109, 122, 53}, },
            {{48, 113, -35}, {114, 114, 88}, {115, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 115, 53}, {116, 116, 89}, {117, 122, 53}, },
            {{48, 115, -66}, {116, 116, 90}, {117, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 104, 53}, {105, 105, 91}, {106, 122, 53}, },
            {{48, 95, -24}, {97, 97, 92}, {98, 122, 53}, },
            {{48, 95, -24}, {97, 97, 93}, {98, 122, 53}, },
            {{48, 95, -24}, {97, 97, 94}, {98, 122, 53}, },
            {{48, 95, -24}, {97, 116, 53}, {117, 117, 95}, {118, 122, 53}, },
            {{48, 104, -69}, {105, 105, 96}, {106, 122, 53}, },
            {{123, 125, -41}, },
            {},
            {{48, 57, 75}, {69, 69, 47}, },
            {{48, 57, 77}, },
            {{48, 57, 77}, },
            {{48, 102, -50}, },
            {{48, 102, -50}, },
            {{48, 102, -50}, },
            {{48, 122, -24}, },
            {{48, 107, -63}, {108, 108, 97}, {109, 122, 53}, },
            {{48, 113, -35}, {114, 114, 98}, {115, 122, 53}, },
            {{48, 103, -29}, {104, 104, 99}, {105, 122, 53}, },
            {{48, 100, -37}, {101, 101, 100}, {102, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 114, -61}, {115, 115, 101}, {116, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 100, -37}, {101, 101, 102}, {102, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 109, -27}, {110, 110, 103}, {111, 122, 53}, },
            {{48, 107, -63}, {108, 108, 104}, {109, 122, 53}, },
            {{48, 109, -27}, {110, 110, 105}, {111, 122, 53}, },
            {{48, 113, -35}, {114, 114, 106}, {115, 122, 53}, },
            {{48, 100, -37}, {101, 101, 107}, {102, 122, 53}, },
            {{48, 107, -63}, {108, 108, 108}, {109, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 100, -37}, {101, 101, 109}, {102, 122, 53}, },
            {{48, 95, -24}, {97, 102, 53}, {103, 103, 110}, {104, 122, 53}, },
            {{48, 115, -66}, {116, 116, 111}, {117, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 115, -66}, {116, 116, 112}, {117, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 100, -37}, {101, 101, 113}, {102, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 100, -37}, {101, 101, 114}, {102, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 113, -35}, {114, 114, 115}, {115, 122, 53}, },
            {{48, 122, -24}, },
        }
        { // COMMENT
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {35, 35, 6}, {37, 37, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {47, 47, 14}, {48, 48, 15}, {49, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {65, 90, 22}, {91, 91, 23}, {93, 93, 24}, {95, 95, 22}, {97, 97, 25}, {98, 98, 26}, {99, 99, 27}, {100, 100, 28}, {101, 101, 29}, {102, 102, 30}, {103, 104, 22}, {105, 105, 31}, {106, 109, 22}, {110, 110, 32}, {111, 111, 33}, {112, 112, 34}, {113, 113, 22}, {114, 114, 35}, {115, 115, 36}, {116, 116, 37}, {117, 118, 22}, {119, 119, 38}, {120, 122, 22}, {123, 123, 39}, {125, 125, 40}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{0, 33, 41}, {34, 34, 42}, {35, 65535, 41}, },
            {{0, 9, 43}, {10, 10, 44}, {11, 65535, 43}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 45}, },
            {},
            {{46, 46, 46}, {48, 57, 16}, {69, 69, 47}, {120, 120, 48}, },
            {{46, 69, -17}, },
            {},
            {},
            {{60, 60, 49}, {61, 61, 50}, },
            {},
            {{61, 61, 51}, },
            {{48, 57, 52}, {65, 90, 53}, {95, 95, 53}, {97, 122, 53}, },
            {},
            {},
            {{48, 95, -24}, {97, 109, 53}, {110, 110, 54}, {111, 122, 53}, },
            {{48, 95, -24}, {97, 110, 53}, {111, 111, 55}, {112, 122, 53}, },
            {{48, 95, -24}, {97, 103, 53}, {104, 104, 56}, {105, 122, 53}, },
            {{48, 110, -28}, {111, 111, 57}, {112, 122, 53}, },
            {{48, 95, -24}, {97, 97, 58}, {98, 107, 53}, {108, 108, 59}, {109, 109, 53}, {110, 110, 60}, {111, 122, 53}, },
            {{48, 95, -24}, {97, 97, 61}, {98, 110, 53}, {111, 111, 62}, {112, 122, 53}, },
            {{48, 95, -24}, {97, 101, 53}, {102, 102, 63}, {103, 109, 53}, {110, 110, 64}, {111, 122, 53}, },
            {{48, 110, -28}, {111, 111, 65}, {112, 122, 53}, },
            {{48, 95, -24}, {97, 113, 53}, {114, 114, 66}, {115, 122, 53}, },
            {{48, 113, -35}, {114, 114, 67}, {115, 122, 53}, },
            {{48, 95, -24}, {97, 100, 53}, {101, 101, 68}, {102, 122, 53}, },
            {{48, 95, -24}, {97, 98, 53}, {99, 99, 69}, {100, 115, 53}, {116, 116, 70}, {117, 122, 53}, },
            {{48, 113, -35}, {114, 114, 71}, {115, 122, 53}, },
            {{48, 103, -29}, {104, 104, 72}, {105, 122, 53}, },
            {{123, 123, 73}, {125, 125, 74}, },
            {},
            {{0, 65535, -7}, },
            {},
            {{0, 65535, -8}, },
            {},
            {{46, 46, 46}, {48, 57, 45}, {69, 69, 47}, },
            {{48, 57, 75}, },
            {{45, 45, 76}, {48, 57, 77}, },
            {{48, 57, 78}, {65, 70, 79}, {97, 102, 80}, },
            {},
            {},
            {},
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 99, 53}, {100, 100, 81}, {101, 122, 53}, },
            {{48, 110, -28}, {111, 111, 82}, {112, 122, 53}, },
            {{48, 95, -24}, {97, 97, 83}, {98, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 98, -38}, {99, 99, 84}, {100, 122, 53}, },
            {{48, 95, -24}, {97, 114, 53}, {115, 115, 85}, {116, 122, 53}, },
            {{48, 99, -56}, {100, 100, 86}, {101, 122, 53}, },
            {{48, 95, -24}, {97, 107, 53}, {108, 108, 87}, {109, 122, 53}, },
            {{48, 113, -35}, {114, 114, 88}, {115, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 115, 53}, {116, 116, 89}, {117, 122, 53}, },
            {{48, 115, -66}, {116, 116, 90}, {117, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 104, 53}, {105, 105, 91}, {106, 122, 53}, },
            {{48, 95, -24}, {97, 97, 92}, {98, 122, 53}, },
            {{48, 95, -24}, {97, 97, 93}, {98, 122, 53}, },
            {{48, 95, -24}, {97, 97, 94}, {98, 122, 53}, },
            {{48, 95, -24}, {97, 116, 53}, {117, 117, 95}, {118, 122, 53}, },
            {{48, 104, -69}, {105, 105, 96}, {106, 122, 53}, },
            {{123, 125, -41}, },
            {},
            {{48, 57, 75}, {69, 69, 47}, },
            {{48, 57, 77}, },
            {{48, 57, 77}, },
            {{48, 102, -50}, },
            {{48, 102, -50}, },
            {{48, 102, -50}, },
            {{48, 122, -24}, },
            {{48, 107, -63}, {108, 108, 97}, {109, 122, 53}, },
            {{48, 113, -35}, {114, 114, 98}, {115, 122, 53}, },
            {{48, 103, -29}, {104, 104, 99}, {105, 122, 53}, },
            {{48, 100, -37}, {101, 101, 100}, {102, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 114, -61}, {115, 115, 101}, {116, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 100, -37}, {101, 101, 102}, {102, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 109, -27}, {110, 110, 103}, {111, 122, 53}, },
            {{48, 107, -63}, {108, 108, 104}, {109, 122, 53}, },
            {{48, 109, -27}, {110, 110, 105}, {111, 122, 53}, },
            {{48, 113, -35}, {114, 114, 106}, {115, 122, 53}, },
            {{48, 100, -37}, {101, 101, 107}, {102, 122, 53}, },
            {{48, 107, -63}, {108, 108, 108}, {109, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 100, -37}, {101, 101, 109}, {102, 122, 53}, },
            {{48, 95, -24}, {97, 102, 53}, {103, 103, 110}, {104, 122, 53}, },
            {{48, 115, -66}, {116, 116, 111}, {117, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 115, -66}, {116, 116, 112}, {117, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 100, -37}, {101, 101, 113}, {102, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 100, -37}, {101, 101, 114}, {102, 122, 53}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 113, -35}, {114, 114, 115}, {115, 122, 53}, },
            {{48, 122, -24}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 0, 0, 0, 0, -1, -1, 18, 19, 20, 16, 14, 13, 15, 17, 44, 44, 21, 38, 34, 33, 36, 46, 29, 30, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 31, 32, -1, 41, -1, 42, -1, -1, -1, -1, 1, 35, 37, 46, 46, 46, 46, 46, 24, 46, 46, 46, 46, 46, 6, 46, 46, 12, 46, 46, 46, 46, 46, 46, -1, 43, 45, -1, 45, 44, 44, 44, 11, 46, 46, 46, 46, 9, 46, 25, 46, 10, 46, 46, 46, 46, 46, 46, 4, 2, 26, 7, 46, 46, 46, 5, 39, 46, 22, 46, 22, 46, 40, 8, 23, 46, 3, },
        // COMMENT
        {-1, 0, 0, 0, 0, -1, -1, 18, 19, 20, 16, 14, 13, 15, 17, 44, 44, 21, 38, 34, 33, 36, 46, 29, 30, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 31, 32, -1, 41, -1, 42, -1, -1, -1, -1, 1, 35, 37, 46, 46, 46, 46, 46, 24, 46, 46, 46, 46, 46, 6, 46, 46, 12, 46, 46, 46, 46, 46, 46, -1, 43, 45, -1, 45, 44, 44, 44, 11, 46, 46, 46, 46, 9, 46, 25, 46, 10, 46, 46, 46, 46, 46, 46, 4, 2, 26, 7, 46, 46, 46, 5, 39, 46, 22, 46, 22, 46, 40, 8, 23, 46, 3, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMMENT = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
